### PR TITLE
color output & zsh+bash autocompletion

### PR DESCRIPTION
**Pull request by Albonycal**
some basic colors added by default.. no flag required.. these colors will not affect the output by the securitytrails api..
colors are only added on the `haktrails usage` & `haktrails` (examples) 
Thank You 
:p bounty pls (this is necessary)

### CODE REVIEW

**Comment by Albonycal** [comment]
Zsh & bash auto completions added

**Comment by ghoeffner** [comment]
Oh, that's great! Autocomplete is really handy.

**Comment by Albonycal** [comment]
Thanks :) updating the Readme now

**Comment by hakluke** [comment]
Love it! Thanks @Albonycal !

**Comment by Albonycal** [comment]
😃

**Pull request merged**
